### ISSUE TITLE
Time complexity of iter

### ISSUE THREAD

**Issue by Risto-Stevcev** [bodil/im-rs#29]
What's the time complexity of the `iter` methods?
I think they should be added to the docs too

**Comment by bodil** [comment]
I agree, I noticed the omission recently and have started documenting trait methods where relevant instead of relying on the inherited documentation. I'll be going through them before the next release to make sure they're all documented.

Until then, `ConsList` should be O(1) on `next()` and the rest should be generally O(1) amortised with O(log₆₄ n) in the worst case.

**Comment by Risto-Stevcev** [comment]
Nice, thanks :slightly_smiling_face:

**Comment by bodil** [comment]
Going to close this and just move it to the release checklist, but please let me know if you're missing any more timings.
