### ISSUE TITLE
Surprising performance on `HashMap::update_with`

### ISSUE THREAD

**Issue by Gastove** [bodil/im-rs#56]
Hello! 

Using this library, I ran in to `HashMap::update_with` being slower than I'd expected. I figured I'd post the demonstration case here. Perhaps this performance is expected, and I've just miss-understood the time complexity of `update_with`! Perhaps this will be unexpected to someone else as well.

I'm counting the frequency of integers in a long vector, building a `HashMap<i32, i32>`. My initial plan was to use an `im::HashMap` for this, because the API of `update_with` is so much nicer than doing this with a `std::collections::HashMap`. However, using an `im::HashMap` is slower than I was expecting. To demonstrate, I did a simple comparison, logging out the `SystemTime::now().elapsed()` after calling each of these functions:

```
use im::HashMap as ImHashMap;
use std::collections::HashMap as StdHashMap;

fn immutable_hash_map(v: &Vec<i32>) -> ImHashMap<i32, i32> {
    v.iter()
        .fold(ImHashMap::new(), |f, i| f.update_with(*i, 1, |o, n| o + n))
}

fn mutable_hash_map(v: &Vec<i32>) -> StdHashMap<i32, i32> {
    v.iter().fold(StdHashMap::new(), |mut f, i| {
        if f.contains_key(&i) {
            let v = f.get(&i).unwrap();
            f.insert(*i, v + 1);
            f
        } else {
            f.insert(*i, 1);
            f
        }
    })
}
```

Providing a `Vec` of a million `i32`s, the `std::collections::HashMap` version completes in about 185 miliseconds. The `im::HashMap` version, on the other hand, takes a touch over 5 seconds. Slow enough to catch me off guard. 

Reading over the documentation, I do see that `update_with` has a time complexity of `O(log n)`. Does this sound like the expected performance for this operation?

**Comment by andrewhickman** [comment]
I happened to be writing a custom allocator with some logging when I saw this, so I gave it a run (using a Vec of 100 i32s this time) 
[immutable_hash_map](https://gist.github.com/andrewhickman/d853676ba11093f04cb016372756e58b)
[mutable_hash_map](https://gist.github.com/andrewhickman/b48c00617bdc53d858cd8a9ed3c686bd).
Definitely looks like the allocations are to blame

**Comment by bodil** [comment]
This isn't unexpected - `update_with` creates a new `HashMap`, and thus holds on to the previous copy, necessitating log n clones for every operation, where `insert` would efficiently mutate the existing `HashMap` if you're the sole owner. This is one of the operations I've held on to from the pre-mutable version of the library because it's so immediately familiar to functional programmers, and I wonder if that may have been a mistake.

If you use the same code for the immutable map as you did for the mutable map, you should see the immutable version perform similarly to (though still roughly 2x slower than) the mutable version.

I'd rewrite them both using the `Entry` API, though, it seems to be a better fit for this job and runs about 25% faster than the mutable fold above, aside from being much more concise:

```rust
fn entry_loop(v: &[i32]) -> HashMap<i32, i32> {
    let mut f = HashMap::new();
    for i in v.iter().cloned() {
        let mut entry = f.entry(i).or_insert(0);
        *entry += 1;
    }
    f
}
```
