### ISSUE TITLE
Using Vector as immutable Deque

### ISSUE THREAD

**Issue by AljoschaMeyer** [bodil/im-rs#86]
A mutable reference to a Vector supports amortized O(1) push/pop operations. But there doesn't seem to be a way to use Vector as an efficient immutable deque (which would need O(1)* functions à la `fn push(&self, A) -> Self` and `fn pop(&self) -> (Self, Option<A>)`). Am I missing something, or is this impossible with this library? And if it's the latter: Is this a fundamental limitation of the data structure, or an implementation issue?

In any case, thanks for the great crate :)

**Comment by AljoschaMeyer** [comment]
Taking another look at it, my understanding is that while `Vector::front` is O(log n) in the worst-case, this worst case is amortized in the sense that calling `front` on n vectors of lengths 1, ..., n is in O(n) overall (and analogously for `skip(1)` and similar methods). Is this correct?

**Comment by bodil** [comment]
Methods like these were actually deliberately removed to avoid the tendency of people coming from languages with immutable values to use them without thinking, because the mutable versions are generally faster by at least an order of magnitude, and it's almost always better to use them in the same way you'd use Rust's mutable data structures and snapshot using `Clone::clone()` when necessary. Think [Clojure's transients](https://clojure.org/reference/transients), but by default, and `clone()` fixes the transient value into a persistent data structure.

In your case, an immutable push would be `let new_deque = deque.clone().push_back(value);` and pop would be `let mut new_deque = deque.clone(); let popped_value = new_deque.pop_back(value);`. `clone()` is O(1) and basically instantaneous, but it has an effect on the following operations, as it necessitates an immutable update rather than a mutable one.

Oh, and the timings for `front()` aren't quite right - it'll be O(log n) only if there's no element in the two head chunks and you have to walk the RRB tree, but it's quite likely the head element is going to be in a head chunk and thus O(1), unless you've built the vector entirely from the back. The converse is true for `back()`. It's not technically amortised O(1), but it's something in the vicinity. The documentation could probably stand to talk a bit more about the head/tail chunk optimisations.

**Comment by AljoschaMeyer** [comment]
> Methods like these were actually deliberately removed to avoid the tendency of people coming from languages with immutable values to use them without thinking [...]

That makes sense. As a bit of context, I'm coming from the opposite direction: Sketching a naive but correct interpreter for a language with immutable values. Specifying correct complexity bounds is quite important to me since those will set the frame for future, more optimized implementations. Technically the exact behavior of this crate doesn't change the language specification, but I do need to specify realistic bounds...

> Oh, and the timings for front() aren't quite right - it'll be O(log n) only if there's no element in the two head chunks and you have to walk the RRB tree, but it's quite likely the head element is going to be in a head chunk and thus O(1), unless you've built the vector entirely from the back.

But that's exactly what happens when using a Vector as a fifo queue, isn't it? Fifo `pop` being O(log n) seems kinda scary. Or do `push_backs` spill over once the tail chunk has been filled, such that it's O(1)* once the Vector becomes large enough?

I'm reading the papers now, so I can hopefully answer those questions myself soon enough - unless the implementation does anything funky.

**Comment by AljoschaMeyer** [comment]
Ok, from what I'm understanding, the [paper](http://deepsea.inria.fr/pasl/chunkedseq.pdf) only guarantees O(1)* deque operations for the bootstrapped version, *not* for an arbitrary sequence augmented with a single pair of front/back chunks (which is what this crate does?). Once these chunks are "exhausted", push/pop performance degrades to that of the underlying sequence (an rrb tree in this crate).

> Consider a sequence (f′, f, m, b, b′). If f′is empty, we populate it as follows. If f is not empty, in which case it must be full, we swap f with f′. Otherwise, assume f to be empty. **If m is not empty, we pop from m**, obtaining a nonempty chunk c and a new middle sequence m′; we then update the sequence to (c, f, m′, b, b′). [...]

The bold part is the performance degradation. For the bootstrapped structure, popping from m is O(1)* again, but for the rrb it is not.

In a fifo setting (e.g. pairing push-front with pop-back), we'd get the degradation immediately, in a lifo setting the degradation only happens for sequences of length at least 2*chunk_capacity.

Is this understanding correct, is this how the "not technically amortised O(1), but it's something in the vicinity" part behaves?

---

Intuitively it feels like it should be possible to pass data "through" an empty rrb tree into the other inner chunk, so that a fifo doesn't degrade immediately. But that still only provides amortized O(1) for sequences below a certain length :disappointed: A more principled solution could try to transfer data between the rrb and the inner chunks in bulk rather than one-by-one. But that seems to go beyond quick tinkering, and is probably something the authors considered and rejected...

**Comment by bodil** [comment]
There's no direct push/pop on the RRB tree on either side - it will only push whole chunks to the tree once the edge chunks fill up, and pop whole chunks off it into the edge chunks when they're empty (eg. `pop_front` where both head chunks are empty will pull a whole chunk off the front of the tree into `outer_f` and pop the head element from that, so only 1 in 64 consecutive pops should touch the RRB). It's only when you start splitting and merging that the tree could contain underfull leaf nodes.

And, yes, the chunking is just an additional optimisation on top of the RRB, to avoid underfull leaves as much as possible and to provide slightly better performance (both on complexity and on actual CPU time) on push/pop, but that isn't to say the RRB itself is dog slow - it's still going to be O(log<sub>k</sub>k n) on every op, though, unless you cache the head/tail chunks somehow.

`Vector` would probably not be my first choice if I wanted a data structure optimised for FIFO queues, but with the edge chunking it's still going to perform pretty well for a generic list type structure.

**Comment by AljoschaMeyer** [comment]
Thanks, that cleared things up for me.
