### ISSUE TITLE
Return new Vector from push functions

### ISSUE THREAD

**Issue by bugeats** [bodil/im-rs#92]
Forgive me, I'm just learning Rust. It's possible I'm missing something fundamental here.

I don't understand why `<Vector>#push_front` returns an empty tuple instead of the new Vector that was just created. Why is this library considered immutable if you need to set the var as mut? Example from the docs:

```rust
let mut vec = vector![5, 6, 7];
vec.push_front(4);
assert_eq!(vector![4, 5, 6, 7], vec);
```

I would expect something closer to this:

```rust
let vec = vector![5, 6, 7];
let vec2 = vec.push_front(4);
assert_eq!(vector![4, 5, 6, 7], vec2);
```

**Comment by bodil** [comment]
The version you expect is slow, and usually needlessly so, which is why I removed most methods with this kind of signature a while back. The data structures are still immutable, but only when they need to be: `clone()` is cheap and will share structure, and the user is expected to explicitly call it when needed, rather than having every operation essentially include an automatic clone.

Generally, when there's only one reference held to a persistent data structure, we're able to modify it mutably, coming close to the performance of `std::collections` equivalents. When you `clone()` it, there are multiple references to it, meaning that when we perform a modification we first have to clone the parts of the data structure that are being modified. We generally want to avoid that as much as we can, because it can slow down operations by as much as an order of magnitude.

Suppose you have a function that takes a vector and performs several `push_front()` operations in a loop, returning the updated vector. If each `push_front()` returns a new vector, preserving the previous value, it means we're constantly keeping two references to the vector around, so every `push_front()` has to first copy parts of the data structure before being able to modify it. If, instead, we `clone()` the data structure at the start of the function before going into the loop, it's likely that only the first `push_front()` will actually have to do the copying work, allowing the subsequent operations to run significantly faster.

This is the same idea as in Clojure's [transients](https://clojure.org/reference/transients) and data structure operations inside the ST monad in Haskell, except that Rust allows us to actually inspect the reference count on tree nodes directly, so that we don't have to explicitly declare data structures to be temporarily mutable and turn them explicitly back into persistent versions before they leave the local scope - we can just look at their reference counters to tell whether we need to copy-on-write or just go ahead and write directly. The only price you have to pay is that you have to explicitly `clone()` any state you want to preserve.

Hope that makes sense. This is a question that comes up a lot, especially from surprised high level FP programmers, I should probably put an explanation in the docs...

**Comment by bodil** [comment]
See also #56 for an example of the performance issues.

**Comment by bugeats** [comment]
Thank you for the detailed explanation. It gave me an idea about how to manage the clone operations in a way that's more like what a FP programmer would expect. What do you think of something like this?

```rust
let vec1 = vector![5, 6, 7];
let vec2 = vec1.transaction(|vec| {
    vec.push_front(4);
    vec.push_back(5);
    vec.push_front(6);
})
assert_eq!(vector![6, 4, 5, 6, 7, 5], vec2);
```
