### ISSUE TITLE
Provide new and unit implementations when not using RandomState as the hasher

### ISSUE THREAD

**Issue by dwightguth** [bodil/im-rs#93]
the new and unit methods for HashSet and HashMap are implemented on the HashSet<A, RandomState> and HashMap<A, RandomState> types. This means you can't call them on any other type that implements BuildHasher + Default, even though ostensibly you should be able to. it's possible to work around this by calling the with_hasher method and passing it the same hasher every single time, but this is unnecessarily cumbersome. It would be better if these methods were implemented in order to work with any BuildHasher that implements the right traits.

**Comment by bodil** [comment]
This is because of type inference troubles - regardless of the `S = RandomState` in the type declaration, `HashMap::new()` will complain that `S` is unresolved if you use it without specific type annotations, so I've left it implemented only for `S = RandomState` because the alternative is worse. You can still use `HashMap::default()` to construct an empty map with any `S: BuildHasher + Default`.
